function [rmse_struct] = get_rmse_struct(fol)

rmse_vars = ['hs_sw_rmse_ww3', 'hs_sw_rmse_ww3_br', 'hs_sw_rmse_pred', ...
    'hs_ss_rmse_ww3', 'hs_ss_rmse_ww3_br', 'hs_ss_rmse_pred', ...
    'rmse_pred_SW', 'rmse_ww3_SW', 'rmse_pred_SS', 'rmse_ww3_SS', ...
    'tm_sw_rmse_pred', 'tm_ss_rmse_pred', 'tm_sw_rmse_ww3', 'tm_ss_rmse_ww3'];

% [hs_sw_rmse_ww3, hs_sw_rmse_ww3_br, hs_sw_rmse_pred, hs_ss_rmse_ww3, ...
%     hs_ss_rmse_ww3_br, hs_ss_rmse_pred, rmse_pred_SW, rmse_ww3_SW, ...
%     rmse_pred_SS, rmse_ww3_SS] = get_rmse( fol );

[hs_sw_rmse_ww3, hs_sw_rmse_ww3_br, hs_sw_rmse_pred, hs_ss_rmse_ww3, ...
    hs_ss_rmse_ww3_br, hs_ss_rmse_pred, rmse_pred_SW, rmse_ww3_SW, ...
    rmse_pred_SS, rmse_ww3_SS, tm_sw_rmse_pred, tm_ss_rmse_pred, ...
    tm_sw_rmse_ww3, tm_ss_rmse_ww3] = get_rmse( fol );


rmse_struct = struct( ...
    'fol', fol, ...
    'hs_sw_rmse_ww3', hs_sw_rmse_ww3, ...
    'hs_sw_rmse_ww3_br', hs_sw_rmse_ww3_br, ...
    'hs_sw_rmse_pred', hs_sw_rmse_pred, ...
    'hs_ss_rmse_ww3', hs_ss_rmse_ww3, ...
    'hs_ss_rmse_ww3_br', hs_ss_rmse_ww3_br, ...
    'hs_ss_rmse_pred', hs_ss_rmse_pred, ...
    'rmse_pred_SW', rmse_pred_SW, ...
    'rmse_ww3_SW', rmse_ww3_SW, ...
    'rmse_pred_SS', rmse_pred_SS, ...
    'rmse_ww3_SS', rmse_ww3_SS, ...
    'tm_sw_rmse_pred', tm_sw_rmse_pred, ...
    'tm_ss_rmse_pred', tm_ss_rmse_pred, ...
    'tm_sw_rmse_ww3', tm_sw_rmse_ww3, ...
    'tm_ss_rmse_ww3', tm_ss_rmse_ww3 ...        
);